export const ALLOWED_AGENTS = [
  'ORION_AGENT',
  'PLAN_AGENT',
  'DESIGN_ALCHEMIST_AGENT',
  'FRONTEND_MEISTER_AGENT',
  'BACKEND_ARCHITEKT_AGENT',
  'QA_GURU_AGENT',
  'OPTIMIERER_AGENT',
  'DOKUMENTATION_AGENT'
] as const;

export const AGENT_LIST_STRING = ALLOWED_AGENTS.join(', ');
